<a href="https://colab.research.google.com/github/dawood1000/Machine-Learning-in-90-days/blob/master/Section%201-%20Python%20Crash%20Course/3-Numpy%20Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [13]:
## initially Lets import numpy

import numpy as np

In [14]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [15]:
print(arr)

[1 2 3 4 5]


In [16]:
type(arr)

numpy.ndarray

In [17]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [18]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [19]:
type(arr)

numpy.ndarray

In [20]:
## check the shape of the array

arr.shape

(3, 5)

### Indexing

In [21]:
## Accessing the array elements

arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [24]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [25]:
arr[1:2, 1:3]

array([[3, 4]])

In [ ]:
arr

In [ ]:
arr1[:,3:]

In [ ]:
arr

In [ ]:
arr[3:]=100

In [ ]:
arr

In [ ]:
### Some conditions very useful in Exploratory Data Analysis

val=2

arr[arr<3]

In [ ]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

In [ ]:
arr1=np.arange(0,10).reshape(2,5)

In [ ]:
arr2=np.arange(0,10).reshape(2,5)

In [ ]:
arr1*arr2

In [ ]:
np.ones((2,5),dtype=int)

In [ ]:
## random distribution
np.random.rand(3,3)

In [ ]:
arr_ex=np.random.randn(4,4)

In [ ]:
arr_ex

In [ ]:
import seaborn as sns

In [ ]:
sns.distplot(pd.DataFrame(arr_ex.reshape(16,1)))

In [ ]:
np.random.randint(0,100,8).reshape(4,2)

In [ ]:
np.random.random_sample((1,5))